# Generated by Django 6.0.3 on 2026-04-15 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='EmployeeTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Desde')),
                ('end_datetime', models.DateTimeField(verbose_name='Hasta')),
                ('reason', models.CharField(blank=True, max_length=150, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_off_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_blocks', to='reservas.employee', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Bloqueo de horario',
                'verbose_name_plural': 'Bloqueos de horario',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SalonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dueña/o'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='reservas.salon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de peluquería',
                'verbose_name_plural': 'Membresías de peluquería',
                'unique_together': {('user', 'salon')},
            },
        ),
    ]
