# Generated by Django 6.0.3 on 2026-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_employee_user_employeetimeoff_salonmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingitem',
            options={'ordering': ['order', 'start_datetime'], 'verbose_name': 'Bloque de trabajo', 'verbose_name_plural': 'Bloques de trabajo'},
        ),
        migrations.AddField(
            model_name='salon',
            name='deposit_enabled',
            field=models.BooleanField(default=False, verbose_name='Seña activa'),
        ),
        migrations.AddField(
            model_name='salon',
            name='deposit_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje de seña'),
        ),
    ]
