# Generated by Django 6.0.3 on 2026-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_appointment_status_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='deposit_enabled',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_choice',
            field=models.CharField(choices=[('none', 'Sin pago'), ('deposit', 'Seña'), ('full', 'Pago total')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_required_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'No requerido'), ('pending', 'Pendiente'), ('reported', 'Informado'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='payment_instructions',
            field=models.TextField(blank=True, verbose_name='Instrucciones de pago'),
        ),
        migrations.AddField(
            model_name='salon',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transferencia'), ('integrated', 'Pago integrado'), ('both', 'Transferencia y pago integrado')], default='transfer', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='salon',
            name='payment_policy',
            field=models.CharField(choices=[('none', 'Sin pago online'), ('deposit_required', 'Seña obligatoria'), ('full_optional', 'Pago total opcional'), ('full_required', 'Pago total obligatorio')], default='none', max_length=30, verbose_name='Política de pago'),
        ),
    ]
