# Generated by Django 6.0.3 on 2026-04-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_salon_deposit_enabled_booking_payment_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='payment_policy',
        ),
        migrations.AddField(
            model_name='salon',
            name='allow_full_payment',
            field=models.BooleanField(default=False, verbose_name='Permitir pago total'),
        ),
        migrations.AddField(
            model_name='salon',
            name='deposit_enabled',
            field=models.BooleanField(default=False, verbose_name='Requerir seña'),
        ),
        migrations.AddField(
            model_name='salon',
            name='full_payment_required',
            field=models.BooleanField(default=False, verbose_name='Requerir pago total'),
        ),
    ]
