# Generated by Django 6.0.3 on 2026-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_salon_payment_policy_salon_allow_full_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_payment_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
