# Generated by Django 6.0.3 on 2026-05-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_booking_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
