# Generated by Django 6.0.3 on 2026-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_booking_selected_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado el'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_client',
            field=models.BooleanField(default=False, verbose_name='Cancelado por cliente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_manage_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Token de gestión del cliente'),
        ),
        migrations.AddField(
            model_name='salon',
            name='allow_client_cancellation',
            field=models.BooleanField(default=True, verbose_name='Permitir cancelación online por cliente'),
        ),
        migrations.AddField(
            model_name='salon',
            name='allow_client_reschedule',
            field=models.BooleanField(default=False, verbose_name='Permitir modificación online por cliente'),
        ),
        migrations.AddField(
            model_name='salon',
            name='cancellation_limit_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Horas límite para cancelar online'),
        ),
        migrations.AddField(
            model_name='salon',
            name='reschedule_limit_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Horas límite para modificar online'),
        ),
    ]
