# Generated by Django 6.0.3 on 2026-05-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_booking_cancelled_at_booking_cancelled_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para notificaciones'),
        ),
    ]
