# Generated by Django 6.0.3 on 2026-05-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_salon_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notify_by_email',
            field=models.BooleanField(default=False, verbose_name='Recibir notificaciones por email'),
        ),
    ]
