# Generated by Django 6.0.3 on 2026-05-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_employee_email_employee_notify_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_enabled', models.BooleanField(default=False)),
                ('mercadopago_connected', models.BooleanField(default=False)),
                ('mp_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('mp_access_token', models.TextField(blank=True, default='')),
                ('mp_refresh_token', models.TextField(blank=True, default='')),
                ('mp_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('mp_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='reservas.salon')),
            ],
        ),
    ]
