# Generated by Django 6.0.3 on 2026-05-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_salonpaymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='notify_new_bookings_by_email',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones de nuevos turnos por email'),
        ),
    ]
