# Generated by Django 6.0.3 on 2026-05-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_salon_notify_new_bookings_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHourBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hour_blocks', to='reservas.salon', verbose_name='Peluquería')),
            ],
            options={
                'verbose_name': 'Bloque horario de atención',
                'verbose_name_plural': 'Bloques horarios de atención',
                'ordering': ['salon', 'weekday', 'start_time'],
            },
        ),
    ]
