# Generated by Django 6.0.3 on 2026-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_businesshourblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='transfer_account_holder',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Titular de la cuenta'),
        ),
        migrations.AddField(
            model_name='salon',
            name='transfer_alias',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='salon',
            name='transfer_bank_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Banco o billetera'),
        ),
        migrations.AddField(
            model_name='salon',
            name='transfer_cbu',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='CBU/CVU'),
        ),
        migrations.AddField(
            model_name='salon',
            name='transfer_extra_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Instrucciones adicionales para transferencia'),
        ),
        migrations.AddField(
            model_name='salon',
            name='transfer_tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='CUIT/CUIL'),
        ),
    ]
