# Generated by Django 6.0.3 on 2026-05-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_salon_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='payment_method',
            field=models.CharField(choices=[('none', 'Ninguno'), ('transfer', 'Transferencia'), ('integrated', 'Mercado Pago'), ('both', 'Transferencia y Mercado Pago')], default='none', max_length=20, verbose_name='Método de pago'),
        ),
    ]
