# Generated by Django 6.0.3 on 2026-05-15 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_alter_salon_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada el')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_invitations', to='reservas.employee', verbose_name='Profesional')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_staff_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='reservas.salon', verbose_name='Peluquería')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Invitación staff',
                'verbose_name_plural': 'Invitaciones staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
