# Generated by Django 6.0.3 on 2026-05-16 20:16
from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    Salon = apps.get_model("reservas", "Salon")

    used_slugs = set()

    for salon in Salon.objects.all().order_by("id"):
        base_slug = slugify(salon.name) or f"salon-{salon.id}"
        slug = base_slug
        counter = 2

        while slug in used_slugs or Salon.objects.filter(slug=slug).exclude(pk=salon.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        salon.slug = slug
        salon.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0019_staffinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="slug",
            field=models.SlugField(
                max_length=140,
                blank=True,
                null=True,
                verbose_name="Slug público",
                help_text="URL pública del salón. Ejemplo: lux-salon",
            ),
        ),
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="salon",
            name="slug",
            field=models.SlugField(
                max_length=140,
                unique=True,
                blank=True,
                verbose_name="Slug público",
                help_text="URL pública del salón. Ejemplo: lux-salon",
            ),
        ),
    ]