# Generated by Django 6.0.3 on 2026-05-19 01:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_add_salon_slug_safely'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Prueba gratuita'), ('active', 'Activo'), ('past_due', 'Pago vencido'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado')], default='trial', max_length=20, verbose_name='Estado')),
                ('plan', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Pro')], default='basic', max_length=20, verbose_name='Plan')),
                ('monthly_price_ars', models.PositiveIntegerField(default=0, verbose_name='Precio mensual ARS')),
                ('trial_starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio de prueba')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de prueba')),
                ('current_period_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del período actual')),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del período actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='reservas.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Suscripción de salón',
                'verbose_name_plural': 'Suscripciones de salones',
                'ordering': ['-created_at'],
            },
        ),
    ]
