# Generated by Django 6.0.3 on 2026-05-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_salonsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Link al Instagram del negocio.', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='salons/logos/', verbose_name='Logo del negocio'),
        ),
        migrations.AddField(
            model_name='salon',
            name='public_description',
            field=models.TextField(blank=True, default='', help_text='Texto que se muestra en la página pública del negocio.', verbose_name='Descripción pública'),
        ),
    ]
