# Generated by Django 6.0.3 on 2026-06-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_servicecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='reservas.employee', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Horario de trabajo del profesional',
                'verbose_name_plural': 'Horarios de trabajo de profesionales',
                'ordering': ['employee', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['employee', 'weekday', 'is_active'], name='employee_workday_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'weekday', 'start_time', 'end_time'), name='unique_employee_working_hour')],
            },
        ),
    ]
