# Generated by Django 6.0.3 on 2026-06-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_bookingitem_google_calendar_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('block_type', models.CharField(choices=[('holiday', 'Feriado'), ('vacation', 'Vacaciones'), ('personal', 'Ausencia personal'), ('special_closure', 'Cierre especial'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Tipo')),
                ('start_datetime', models.DateTimeField(verbose_name='Desde')),
                ('end_datetime', models.DateTimeField(verbose_name='Hasta')),
                ('all_day', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('show_in_agenda', models.BooleanField(default=True, verbose_name='Mostrar en agenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_availability_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_availability_blocks', to='reservas.employee', verbose_name='Profesional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_availability_blocks', to='reservas.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Bloqueo especial',
                'verbose_name_plural': 'Bloqueos especiales',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['salon', 'start_datetime', 'end_datetime'], name='sp_block_salon_range_idx'), models.Index(fields=['employee', 'start_datetime', 'end_datetime'], name='sp_block_employee_range_idx')],
            },
        ),
    ]
