# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_specialavailabilityblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completado'),
        ),
        migrations.AddField(
            model_name='salon',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False, verbose_name='Onboarding descartado'),
        ),
        migrations.AddField(
            model_name='salon',
            name='onboarding_link_shared',
            field=models.BooleanField(default=False, verbose_name='Link de reservas compartido'),
        ),
    ]
