# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_salon_onboarding_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='onboarding_current_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Paso actual del onboarding'),
        ),
    ]
