# Generated by Django 6.0.3 on 2026-07-08 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0029_salon_onboarding_current_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, max_length=120)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='reservas.salon', verbose_name='Peluqueria')),
            ],
            options={
                'verbose_name': 'Nota interna de cliente',
                'verbose_name_plural': 'Notas internas de clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['salon', 'customer_key'], name='reservas_cu_salon_i_3e7519_idx')],
            },
        ),
    ]
